In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

rand_int2 = np.random.randint(10,90,(10,3) # random numpy array of shape (10,3)

print("Second array", rand_int2)

Second array [[31 59 66 53 62]
 [87 41 64 63 14]
 [21 14 86 66 48]
 [88 34 88 44 26]]
